name: Build and push docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "activity-pub"
      - "yozumina-develop"
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{env.IMAGE_NAME}}

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v3

      - name: Make repository name lowercase
        run: |
          echo REPO_LC=$(echo ${{env.REPO}} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        env:
          REPO: "${{env.REGISTRY}}/${{env.IMAGE_NAME}}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/arm64
          cache-from: type=gha,ref=${{env.REPO_LC}}:build-cache
          cache-to: type=gha,ref=${{env.REPO_LC}}:build-cache,mode=max,image-manifest=true,oci-mediatypes=true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}
